import os
import requests
from dotenv import load_dotenv

load_dotenv()

OLLAMA_URL = "http://localhost:11434/api/generate"

def get_advice(message: str, financial_context: dict = None) -> str:
    ctx = financial_context or {}
    income = ctx.get("income", "Unknown")
    expenses = ctx.get("expenses", "Unknown")
    savings = ctx.get("savings", "Unknown")
    age = ctx.get("age", "Unknown")

    system_prompt = f"""
You are Artha, a highly intelligent, empathetic, and expert financial AI Copilot.
You have perfectly contextual knowledge of the user's current financial situation.
Do NOT give generic advice. Give hyper-specific advice based on precisely these numbers:
- Monthly Income: ₹{income}
- Monthly Expenses: ₹{expenses}
- Current Savings (Corpus): ₹{savings}
- Age: {age}

Rules:
1. Always format responses in clean Markdown.
2. Be direct and avoid generic disclaimers.
3. If the user asks if they can retire early, calculate an approximate 4% rule (annual expenses * 25) vs their current savings.
4. Keep answers concise but strictly actionable. Give real numbers.

User Message: {message}
    """

    try:
        response = requests.post(
            OLLAMA_URL,
            json={
                "model": "llama3",
                "prompt": system_prompt,
                "stream": False
            },
            timeout=30 # local LLMs can be slow
        )
        if response.status_code == 200:
            return response.json().get("response", "No response generated by Ollama.")
        else:
            return f"Ollama Error: {response.text}"
    except requests.exceptions.ConnectionError:
        return "Could not connect to Ollama. Make sure the Ollama app is running locally on your computer."
    except Exception as e:
        return f"Could not fetch AI advice: {str(e)}"
